language: node_js

env:

node_js: 
  - "9"

sudo: enabled

os: ubuntu

before_install:
  - npm install codecov -g
  - npm install -g react-scripts
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g mocha


env:
  - TEST_DIR=client
  - TEST_DIR=.

before_script:

script:
  - cd $TEST_DIR && npm install && npm test
  - cd client && npm run build

after_success:
  - 

cache:
  directories:
    - "client/node_modules"
    - "node_modules"

